# Generated by Django 5.1.15 on 2026-09-11 20:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("deptid", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "dept",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "empid",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^\\d{8}$")],
                    ),
                ),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("addre", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=15)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
                ("admidate", models.DateField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "dept",
                    models.ForeignKey(
                        db_column="deptid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="accounts.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "emplo",
                "ordering": ["empid"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                db_column="manager",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_departments",
                to="accounts.employee",
            ),
        ),
    ]
