# Generated by Django 5.1.15 on 2026-09-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "airportid",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=250)),
                ("city", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                ("zipcode", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "airport",
                "ordering": ["airportid"],
            },
        ),
        migrations.CreateModel(
            name="Airplane",
            fields=[
                (
                    "airplaneid",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=8)),
                ("numseats", models.PositiveIntegerField()),
                ("totalfuel", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "airplane",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("numseats__gt", 0)),
                        name="airplane_numseats_positive",
                    )
                ],
            },
        ),
    ]
