# Generated by Django 5.1.15 on 2026-09-11 20:04

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_department_employee_department_manager"),
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crew",
            fields=[
                ("crewid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "commander",
                    models.ForeignKey(
                        db_column="commander",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crews_as_commander",
                        to="accounts.employee",
                    ),
                ),
                (
                    "copilote",
                    models.ForeignKey(
                        db_column="copilote",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crews_as_copilote",
                        to="accounts.employee",
                    ),
                ),
                (
                    "fachief",
                    models.ForeignKey(
                        db_column="fachief",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crews_as_fachief",
                        to="accounts.employee",
                    ),
                ),
                (
                    "fliattendant1",
                    models.ForeignKey(
                        db_column="fliattendant1",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crews_as_fliattendant1",
                        to="accounts.employee",
                    ),
                ),
                (
                    "fliattendant2",
                    models.ForeignKey(
                        db_column="fliattendant2",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crews_as_fliattendant2",
                        to="accounts.employee",
                    ),
                ),
                (
                    "fliattendant3",
                    models.ForeignKey(
                        db_column="fliattendant3",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crews_as_fliattendant3",
                        to="accounts.employee",
                    ),
                ),
            ],
            options={
                "db_table": "crew",
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("shiftid", models.AutoField(primary_key=True, serialize=False)),
                ("shiftdate", models.DateField()),
                ("begintime", models.TimeField()),
                ("endtime", models.TimeField()),
                (
                    "crew",
                    models.ForeignKey(
                        db_column="crewid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="operations.crew",
                    ),
                ),
            ],
            options={
                "db_table": "shift",
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                ("flightid", models.AutoField(primary_key=True, serialize=False)),
                ("flightdate", models.DateField()),
                ("deptime", models.TimeField()),
                ("arrtime", models.TimeField()),
                ("totpass", models.IntegerField()),
                ("totbagga", models.IntegerField(default=0)),
                (
                    "flightnum",
                    models.CharField(
                        max_length=6,
                        validators=[django.core.validators.RegexValidator("^CB\\d{4}$")],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=Decimal("120.99"), max_digits=7),
                ),
                (
                    "airplane",
                    models.ForeignKey(
                        db_column="airplaneid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights",
                        to="fleet.airplane",
                    ),
                ),
                (
                    "airportarr",
                    models.ForeignKey(
                        db_column="airportarr",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrivals",
                        to="fleet.airport",
                    ),
                ),
                (
                    "airportdep",
                    models.ForeignKey(
                        db_column="airportdep",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departures",
                        to="fleet.airport",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        db_column="shiftid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flights",
                        to="operations.shift",
                    ),
                ),
            ],
            options={
                "db_table": "flight",
                "ordering": ["flightdate", "deptime", "flightnum"],
            },
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(fields=["shiftdate"], name="shift_shiftdate_idx"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(
                condition=models.Q(("begintime__lt", models.F("endtime"))),
                name="shift_begin_before_end",
            ),
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(fields=["flightdate", "deptime"], name="flight_date_deptime_idx"),
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(fields=["flightnum"], name="flight_flightnum_idx"),
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.UniqueConstraint(
                fields=("flightnum", "flightdate"),
                name="flight_flightnum_flightdate_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.CheckConstraint(
                condition=models.Q(("airportdep", models.F("airportarr")), _negated=True),
                name="flight_airports_differ",
            ),
        ),
    ]
