from .view_classes import (
    CrewCreateView,
    CrewDeleteView,
    CrewListView,
    CrewUpdateView,
    FlightCreateView,
    FlightDeleteView,
    FlightGenerateView,
    FlightListView,
    FlightUpdateView,
    ShiftCreateView,
    ShiftDeleteView,
    ShiftListView,
    ShiftUpdateView,
)

__all__ = [
    "CrewCreateView",
    "CrewDeleteView",
    "CrewListView",
    "CrewUpdateView",
    "FlightCreateView",
    "FlightDeleteView",
    "FlightGenerateView",
    "FlightListView",
    "FlightUpdateView",
    "ShiftCreateView",
    "ShiftDeleteView",
    "ShiftListView",
    "ShiftUpdateView",
]
