# Generated by Django 5.1.15 on 2026-09-11 20:04

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_department_employee_department_manager"),
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                ("clientid", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=250)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=30)),
                ("zipcode", models.CharField(max_length=15)),
                ("telephone", models.CharField(max_length=18)),
                ("email", models.EmailField(max_length=100)),
            ],
            options={
                "db_table": "passengers",
                "ordering": ["lastname", "firstname", "clientid"],
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Upper("lastname"),
                        django.db.models.functions.text.Upper("firstname"),
                        name="passengers_name_upper_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Buy",
            fields=[
                ("buyid", models.AutoField(primary_key=True, serialize=False)),
                ("buydate", models.DateField()),
                ("buytime", models.TimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "emp",
                    models.ForeignKey(
                        db_column="empid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="accounts.employee",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        db_column="clientid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buys",
                        to="sales.passenger",
                    ),
                ),
            ],
            options={
                "db_table": "buy",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "ticketid",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^CB\\d{8}$")],
                    ),
                ),
                (
                    "seat",
                    models.CharField(
                        max_length=3,
                        validators=[django.core.validators.RegexValidator("^[A-F]\\d{2}$")],
                    ),
                ),
                (
                    "buy",
                    models.ForeignKey(
                        db_column="buyid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="sales.buy",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        db_column="clientid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="sales.passenger",
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        db_column="flightid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="operations.flight",
                    ),
                ),
            ],
            options={
                "db_table": "ticket",
            },
        ),
        migrations.AddIndex(
            model_name="buy",
            index=models.Index(fields=["buydate"], name="buy_buydate_idx"),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("flight", "seat"), name="ticket_flight_seat_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("flight", "client"), name="ticket_flight_client_uniq"
            ),
        ),
    ]
